# site settings
title: Blog
subtitle: by Madhav Rathi
email: mdhvrthi@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: India
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/madhavrathi
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/mdhvrthi/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/mdhvrthi

# build settings
markdown: kramdown

sass:
  style: compressed
